from fpdf import FPDF
from io import BytesIO
import pandas as pd
import base64

def generate_risk_report_pdf(inputs, results):
    """Generates a PDF report containing the inputs and prediction results."""

    # Custom PDF class inheriting from FPDF
    class PDF(FPDF):
        def header(self):
            self.set_font('Arial', 'B', 15)
            self.set_text_color(30, 144, 255)  # Dodger Blue
            self.cell(0, 10, 'Lauki Finance: Credit Risk Decision Report', 0, 1, 'C')
            self.set_text_color(0, 0, 0)  # Back to Black
            self.ln(5)

        def footer(self):
            self.set_y(-15)
            self.set_font('Arial', 'I', 8)
            self.cell(0, 10, f'Generated by Model - Page {self.page_no()}', 0, 0, 'C')

    pdf = PDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_font('Arial', '', 12)

    # --- 1. Decision Summary ---
    pdf.set_fill_color(220, 220, 220)
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, 'Decision Summary', 0, 1, 'L', 1)

    pdf.set_font('Arial', '', 12)
    pdf.cell(80, 8, 'Default Probability:', 0)
    pdf.cell(0, 8, f"{results['probability']:.2%}", 0, 1)

    pdf.cell(80, 8, 'Calculated Credit Score:', 0)
    pdf.cell(0, 8, str(results['credit_score']), 0, 1)

    # Final Rating Box
    pdf.ln(3)
    pdf.set_font('Arial', 'B', 16)

    # Set color based on rating for the box background
    if results['rating'] == 'Excellent':
        pdf.set_fill_color(76, 175, 80)  # Green
    elif results['rating'] == 'Poor':
        pdf.set_fill_color(244, 67, 54)  # Red
    else:
        pdf.set_fill_color(255, 152, 0)  # Orange

    pdf.set_text_color(255, 255, 255)  # White text for the box
    pdf.cell(0, 12, f"FINAL RATING: {results['rating'].upper()}", 0, 1, 'C', 1)
    pdf.set_text_color(0, 0, 0)  # Reset text color
    pdf.ln(5)

    # --- 2. Input Parameters Table ---
    pdf.set_font('Arial', 'B', 14)
    pdf.set_fill_color(220, 220, 220)
    pdf.cell(0, 10, 'Applicant and Model Input Parameters', 0, 1, 'L', 1)

    pdf.set_font('Arial', '', 12)
    # Convert inputs dictionary to a DataFrame for easier handling
    df = pd.DataFrame(list(inputs.items()), columns=['Feature', 'Value'])

    # Prepare table headers
    pdf.set_font('Arial', 'B', 10)
    col_width = pdf.w / 2.5
    pdf.cell(col_width, 7, 'Feature', 1, 0, 'C', 0)
    pdf.cell(col_width, 7, 'Value', 1, 1, 'C', 0)

    # Fill table rows
    pdf.set_font('Arial', '', 10)
    for index, row in df.iterrows():
        pdf.cell(col_width, 6, str(row['Feature']), 1, 0, 'L', 0)
        pdf.cell(col_width, 6, str(row['Value']), 1, 1, 'L', 0)


    # Finalize and get the PDF as bytes
    buffer = BytesIO()
    pdf.output(buffer)  # <-- Write directly to the buffer
    return buffer.getvalue()  # <-- Return the bytes from the buffer

